version: '3.7'
services: 
    database:
        container_name: database_stey
        image: mysql:5.7
        restart: always
        ports:
            - "3306:3306"
        environment:
            MYSQL_USER: 'user_stey'
            MYSQL_PASSWORD: '123456'
            MYSQL_ROOT_PASSWORD: '123456'
            MYSQL_DATABASE: 'stey_db'
        volumes:
            - appdbdata:/var/lib/mysql
            - ./docker/sql/steyDB:/docker-entrypoint-initdb.d
    app:
        container_name: app_stey
        build: .
        ports:
            - '8080:8080'
        depends_on: 
            - database
        environment:
            - HOST_DB=database
            - USERNAME_DB=user_stey
            - PASSWORD_DB=123456
            - DATABASE_DB=stey_db
        command: sh -c "cd /var/app/ && npm run dev"
        volumes: 
            - ./app/src:/var/app/src
            - ./app/node_modules:/var/app/node_modules
volumes:
    appdbdata:
        driver: local

networks:
    default: